---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: secureblue-server
description: Default server build, secureblue, for home use

# Use secureblue's hardened Nvidia open-kernel module stream
base-image: ghcr.io/secureblue/securecore-nvidia-open-hardened
image-version: latest

modules:
  - from-file: ../modules/packages.yml
  - from-file: ../modules/fonts.yml
  - from-file: ../modules/brew.yml
  - from-file: ../modules/additional-packages.yml
  - type: signing

nushell-version: none

platforms:
  - linux/amd64
  - linux/amd64/v2
  - linux/arm
  - linux/arm/v6
  - linux/arm/v7
  - linux/arm64
  - linux/riscv64
